# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PomodoroTechnique' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PomodoroTechnique
  pod 'SnapKit'
  pod "CDAlertView"
end
